### ISSUE TITLE
在ListView中不显示

### ISSUE THREAD

**Issue by williamsim** [wusiyi/GeyekRatingBar#1]
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <TextView
        android:id="@+id/tv_name"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="发打发" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/tv_name"
        android:layout_marginLeft="8dp"
        android:layout_marginTop="6dp"
        android:gravity="center_vertical"
        android:orientation="horizontal"
        android:paddingLeft="4dp"
        android:paddingRight="4dp">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="ada" />

        <me.stiky.widget.RatingBar
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:automatic="fully"
            app:isIndicator="false"
            app:numStars="6"
            app:progress="@drawable/btn_rating_star_off_normal"
            app:progressed="@drawable/btn_rating_star_off_selected"
            app:rating="0"
            app:spacing="10dp"
            app:stepSize="0.2" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="SD"
            android:visibility="visible" />
    </LinearLayout>
</RelativeLayout>`
这是我的list item 布局，你可以测试一下，RatingBar没有显示出来，当RatingBar父控件改为固定高度时，才显示出来>

该BUG在onMeasure方法中需要做如下修改:
       ` tempHeight 有可能为0
        mHeight = tempHeight != 0 ? (h > 0 ? tempHeight : height) : height;//edit
        float y = 1;
        if (h > 0 && h != height) {//edit
            y = 1 - h / mStarHeight;
        }`

**Comment by liyonghuan** [comment]
感谢你的提醒，我在项目使用过程中也发生了类似的问题，是在嵌套scrollview的时候不显示。这个问题我会根据你的方法尝试修改一下，如果有更多好的建议可以随时联系我。
